@startuml

(*) --> "user entered BMI"

if "if(m == 0 || isNaN(m))" then
    --> [true] "Calculate BMI\nRedirect to result page"
    --> (*)
else
    --> [false] "Redirect to frontpage"
    --> (*)

@enduml